global:
  app:
    buildType: 'stable'
  ingress:
    enabled: false
    className: ''
    host: affine.pro
    tls: []
  secret:
    secretName: 'server-private-key'
    privateKey: ''
  database:
    user: 'postgres'
    host: 'pg-postgresql'
    port: '5432'
    name: 'affine'
    password: ''
  redis:
    host: 'redis-master'
    port: '6379'
    username: ''
    password: ''
    database: 0
  docService:
    name: 'affine-doc'
    port: 3020
  deployment:
    # change to 'selfhosted' and 'unknown' if this chart is ready to be used for selfhosted deployment
    type: 'affine'
    platform: 'gcp'

graphql:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

sync:
  service:
    type: ClusterIP
    port: 3010
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

renderer:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

doc:
  service:
    type: ClusterIP
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-api-backendconfig"}'

web:
  service:
    type: ClusterIP
    port: 8080
